### ISSUE TITLE
Add StackOverflow question about build process to README

### ISSUE THREAD

**Issue by mizzao** [mizzao/bot.land#57]
https://stackoverflow.com/q/58278709/586086

**Comment by PopGoesTheWza** [comment]
Which question exactly?

Both proposals uses a "typescript" only approach, avoiding the need of webpack/parcel/gulp and similar 3rd party tools.
They also both opted for `tsc --build` mode with a main `tsconfig.json` which references subcomponents (bots and lib)

For each "bot", there are two input files
- a `tsconfig.json` defining the target `.js` file
- an `index.ts` file with the typescript code

Upon `npm run build` / `npm run build-clean` execution, for each "bot" there are three output files

- the target `.js' file to use within the botland application
- its `.d.ts` and `.tsbuildinfo`

**Comment by mizzao** [comment]
Done in #62.
